### PR TITLE
feat(search): display `Cmd` for Mac users

### PR DESCRIPTION
**Pull request by 0xflotus**

### CODE REVIEW

**Comment by 0xflotus** [comment]
Bildschirmfoto 2020-11-26 um 21 56 19

Can you help, please? @innocenzi

**Comment by innocenzi** [comment]
The issue was that `window` is only accessible on the client side, and not at generation-time. Can you check the preview and ensure that my changes work fine?

**Comment by 0xflotus** [comment]
> The issue was that `window` is only accessible on the client side, and not at generation-time. Can you check the preview and ensure that my changes work fine?

All fine. Perfect! Thanks.

**Comment by innocenzi** [comment]
Thank you for your contributions!

**Pull request merged**
